const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  ptyCreate: (cols, rows, opts = {}) => ipcRenderer.invoke('pty:create', { cols, rows, ...opts }),
  ptyInput: (id, data) => ipcRenderer.send('pty:input', { id, data }),
  ptyResize: (id, cols, rows) => ipcRenderer.send('pty:resize', { id, cols, rows }),
  ptyKill: (id) => ipcRenderer.send('pty:kill', { id }),
  ptyMute: (id, ms) => ipcRenderer.send('pty:mute', { id, ms }),
  onPtyData: (cb) => ipcRenderer.on('pty:data', (_e, m) => cb(m)),
  onPtyExit: (cb) => ipcRenderer.on('pty:exit', (_e, m) => cb(m)),
  themeGet: () => ipcRenderer.invoke('theme:get'),
  themeSave: (theme) => ipcRenderer.invoke('theme:save', theme),
  themeOpenFile: (which) => ipcRenderer.send('theme:openFile', which),
  onThemeChanged: (cb) => ipcRenderer.on('theme:changed', (_e, m) => cb(m)),
  keysGet: () => ipcRenderer.invoke('keys:get'),
  sessionGet: () => ipcRenderer.invoke('session:get'),
  sessionSave: (layout) => ipcRenderer.send('session:layout', layout),
  onOpenDir: (cb) => ipcRenderer.on('session:openDir', (_e, dir) => cb(dir)),
  onKeysChanged: (cb) => ipcRenderer.on('keys:changed', (_e, m) => cb(m)),
  glassInfo: () => ipcRenderer.invoke('glass:info'),
  diagReport: (data) => ipcRenderer.send('diag:report', data),
  pickDir: () => ipcRenderer.invoke('dialog:pickDir'),
  fontsList: () => ipcRenderer.invoke('fonts:list'),
  profilesList: () => ipcRenderer.invoke('profiles:list'),
  gitBranch: (cwd) => ipcRenderer.invoke('git:branch', cwd),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  notifyCommand: (info) => ipcRenderer.send('notify:command', info),
  onAgentReveal: (cb) => ipcRenderer.on('agent:reveal', (_e, id) => cb(id)),
  resolvePaths: (cwd, candidates) => ipcRenderer.invoke('paths:resolve', { cwd, candidates }),
  openPath: (opts) => ipcRenderer.invoke('paths:open', opts),
  agentsGetConfig: () => ipcRenderer.invoke('agents:getConfig'),
  agentsAddSpace: () => ipcRenderer.invoke('agents:addSpace'),
  agentsRemoveSpace: (path) => ipcRenderer.invoke('agents:removeSpace', path),
  agentsSpawn: (opts) => ipcRenderer.invoke('agents:spawn', opts),
  agentsTrack: (opts) => ipcRenderer.send('agents:track', opts),
  agentsSelectDiff: (agentId) => ipcRenderer.send('agents:selectDiff', agentId),
  worktreesList: () => ipcRenderer.invoke('worktrees:list'),
  worktreesPrune: () => ipcRenderer.invoke('worktrees:prune'),
  worktreesSelectDiff: (opts) => ipcRenderer.send('worktrees:selectDiff', opts),
  worktreesMerge: (path) => ipcRenderer.invoke('worktrees:merge', path),
  worktreesDiscard: (path) => ipcRenderer.invoke('worktrees:discard', path),
  onAgentStatus: (cb) => ipcRenderer.on('agent:status', (_e, m) => cb(m)),
  onAgentDiff: (cb) => ipcRenderer.on('agent:diff', (_e, m) => cb(m)),
  onAgentDetected: (cb) => ipcRenderer.on('agent:detected', (_e, m) => cb(m)),
  onAgentEnded: (cb) => ipcRenderer.on('agent:ended', (_e, m) => cb(m)),
  agentsGetSessions: () => ipcRenderer.invoke('agents:getSessions'),
  agentsRemoveSession: (cwd) => ipcRenderer.invoke('agents:removeSession', cwd),
  onWinBounds: (cb) => ipcRenderer.on('win:bounds', (_e, m) => cb(m)),
  zoomStep: (dir) => ipcRenderer.invoke('zoom:step', dir),
  onZoom: (cb) => ipcRenderer.on('win:zoom', (_e, m) => cb(m)),
  winMinimize: () => ipcRenderer.send('win:minimize'),
  winMaximize: () => ipcRenderer.send('win:maximize'),
  winClose: () => ipcRenderer.send('win:close'),
  winResizeStart: (edge) => ipcRenderer.send('win:resizeStart', edge),
  winResizeEnd: () => ipcRenderer.send('win:resizeEnd'),
  winNew: () => ipcRenderer.send('win:new'),
  appRelaunch: () => ipcRenderer.send('app:relaunch'),
  onNeedsRestart: (cb) => ipcRenderer.on('app:needsRestart', (_e, m) => cb(m)),
  agentsClaimTab: () => ipcRenderer.invoke('agents:claimTab'),
  agentsReleaseTab: () => ipcRenderer.send('agents:releaseTab')
});
